# Generated by Django 3.2 on 2021-04-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20180602_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('person_num', models.IntegerField(default=0)),
                ('person_max', models.IntegerField(default=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
        ),
    ]
