# Generated by Django 3.2 on 2021-04-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
