# Generated by Django 3.2 on 2021-04-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180602_1007'),
        ('chatroom', '0002_auto_20210412_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.room')),
                ('room_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
        ),
    ]
